name: tv_maze_app
description: "TV Maze App."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^10.1.0
  injectable: ^2.3.0
  get_it: ^7.6.0
  dio: ^5.3.2
  hive: ^2.2.3
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  debounce_throttle: ^2.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  package_info_plus: ^6.0.0
  glass_kit: ^3.0.0
  intl: ^0.18.1
  flutter_keyboard_visibility: ^6.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.3.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/svg/menu/
    - assets/svg/common/
